apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
    release: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
      release: mysql
  template:
    metadata:
      labels:
        app: mysql
        release: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: grafana 
        - name: MYSQL_USER
          value: root 
        - name: MYSQL_PASSWORD
          value: root     
        - name: TZ
          value: Canada/Saskatchewan
      restartPolicy: Always
---
# MySql server external service
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
    release: mysql
spec:
  type: NodePort
  
  selector:
    app: mysql
    release: mysql
  ports:
  - protocol: TCP
    nodePort: 30502
    port: 3306
    targetPort: 3306